# Generated by Django 3.2.8 on 2021-11-21 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmanager',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='p_manager.company'),
        ),
    ]
