
name: Build and push django image to aws ecr
on:
  push:
    branches: [main]
jobs:
  build-and-push:
    name: Build and push to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Update AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli


      - name: Build, Tag, and Push the Image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: pms-repo-001
          IMAGE_TAG: latest
        run: |
          for retry in {1..5}; do
            docker build -t pms-repo-001 .
            docker tag pms-repo-001:latest 519831686957.dkr.ecr.eu-north-1.amazonaws.com/pms-repo-001:latest
            docker push 519831686957.dkr.ecr.eu-north-1.amazonaws.com/pms-repo-001:latest
          done